# Generated by Django 5.1.7 on 2026-03-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emercont', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=1000)),
                ('currlocation', models.CharField(max_length=100)),
                ('coords', models.CharField(max_length=100)),
                ('media', models.FileField(upload_to='')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
