# Generated by Django 5.1.7 on 2026-03-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_emergencyuser_currlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyuser',
            name='coords',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
