# Generated by Django 5.1.7 on 2026-03-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_emergencyuser_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyuser',
            name='file',
        ),
    ]
